name: Feature request
description: Suggest an improvement or new capability
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make Nix-manipulator better.
        The canonical issue tracker is on Codeberg (see CONTRIBUTING.md). If you prefer GitHub, this is still okay.
  - type: checkboxes
    attributes:
      label: Pre-flight
      options:
        - label: I searched existing issues.
          required: true
  - type: textarea
    attributes:
      label: Problem or use case
      description: What are you trying to accomplish?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: What would you like to see implemented?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: Other approaches you have tried or considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Mockups, examples, or related discussions.
  - type: checkboxes
    attributes:
      label: Contribution
      options:
        - label: I can help implement or test this.
          required: false
