name: "Test Nix Build"
on:
  pull_request:
  push:
    branches: *

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: Build the package
      run: nix-build